### ISSUE TITLE
The parameter is incorrect error

### ISSUE THREAD

**Issue by jusw85** [Kaskadee/rpaextract#4] opened 2023-12-08 20:42 UTC
```
(Info) Trying to parse archive using rpaextract.API.RenpyArchiveReader...
(Error) Failed to open archive: The parameter is incorrect. 
```
All rpa files extracted successfully except for 2 files, which give the above error.

**Comment by Kaskadee** [comment] 2023-12-08 23:05
Hi,

that's strange. Can you try [v1.3.3](https://github.com/Kaskadee/rpaextract/releases/tag/v1.3.3)? It probably won't fix the bug, since I guess it has something to do with the compression of the archive, but I added printing the stack trace instead of only the exception message.

EDIT: Also note that I upgraded from .NET 6 to .NET 8

**Comment by jusw85** [comment] 2023-12-09 02:41
```
(Info) Trying to parse archive using rpaextract.API.RenpyArchiveReader...
(Error) Failed to open archive: System.IO.IOException: The parameter is incorrect. : 'C:\Users.....rpa'
   at System.IO.Strategies.FileStreamHelpers.ThrowInvalidArgument(SafeFileHandle handle)
   at System.IO.Strategies.OSFileStreamStrategy.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Strategies.BufferedFileStreamStrategy.Seek(Int64 offset, SeekOrigin origin)
   at rpaextract.API.RenpyArchiveReader.LoadAsync(CancellationToken token) in D:\Kaskadee\Entwicklung\rpaextract\src\rpaextract\API\RenpyArchiveReader.cs:line 70
   at rpaextract.Archive.LoadAsync(FileInfo fi, CancellationToken token) in D:\Kaskadee\Entwicklung\rpaextract\src\rpaextract\Archive.cs:line 91
   at rpaextract.Program.RunOptions(Options options) in D:\Kaskadee\Entwicklung\rpaextract\src\rpaextract\Program.cs:line 47

```

The two files are the largest of the lot, 2.4gb each.

**Comment by Kaskadee** [comment] 2023-12-09 12:39
> The two files are the largest of the lot, 2.4gb each.

Ah, that is probably the cause. Since the file is larger than the maximum value of a 32-bit integer, it caused the offset to overflow into a negative number.

Should be fixed now in [v1.4.0](https://github.com/Kaskadee/rpaextract/releases/tag/v1.4.0 )

**Comment by jusw85** [comment] 2023-12-10 04:46
Works now, thanks!

**Comment by Kaskadee** [comment] 2023-12-10 10:39
That's great.

**Closed as completed by Kaskadee** 2023-12-10 10:39 UTC
Labels: bug
